version: '3.8'

services:
  web:
    container_name: splitter
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/code/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - ENVIRONMENT=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    restart: unless-stopped
    tty: true
    stdin_open: true